### PR TITLE
State Senate support #112 #216 / Handle missing metrics #226

### PR DESCRIPTION
**Pull request by gregallensworth**
This includes merged content from PR 220 and 224, relevant to nodata conditions on state pages. This PR may be smaller and more readable, if those PRs are merged first.

#216 and #112 -- State Senate buttons are now enabled and not opaque nor hidden, and they now load the data as expected.

#226 -- State Senate data brings a condition where a state+year+district may be missing one or more metric outcomes. The state details page has been modified, to handle these conditions.

### CODE REVIEW

**Comment by danrademacher** [comment]
This looks good to me in my local testing. Only known item to confirm with Mike is wording for the PB and MMD tabs when no metric is available, as described here https://github.com/PlanScore/PlanScore/issues/226#issuecomment-366059188

**Comment by migurski** [comment]
How about an active sentence that uses all the words, e.g. “We did not calculate Partisan Bias for California’s 2012 Redistricting Plan” ? Regular, non-bold type is probably fine.

**Comment by migurski** [comment]
Also, for the state houses we have a special behavior on the front page that selects 2014 when you're on 2016 due to poor data availability.

Could State senates get a similar behavior? Maybe even selecting 2012, since 2014 senate data is so sparse.

**Comment by migurski** [comment]
The behavior in this PR looks releasable to me. Let’s hold off on the merge for the moment — I want to check with the team to see if there’s any reason to time this new data release somehow, perhaps delay it by a day or two for media reasons while Pennsylvania Madness is in full effect.

**Comment by migurski** [comment]
All right, this is looking really good! I made it visible here: http://planscore-2020-site-update.s3-website-us-east-1.amazonaws.com/#!2012-statesenate

Nick and Ruth weighed in on the State Senate missing values. Even though the elections in those years are not included, we still have plans that cover them and we should still use them. I suspect this is something that can be resolved in the spreadsheet by adding the appropriate rows. I tested this by adding two rows:

- `'State Senate pre-prod. 2020'!A374:AO374` with a mostly-empty NC2012
- `'Plan IDs'!G690:J690` with an NC5 plan ID for NC2012

This results in coverage for 2012 in NC in the state senates production sheet. If this correctly fills in NC for that year, I can do the remainder.

**Comment by migurski** [comment]
I added NC2012 in ebc0132 and tried it out. Looking good, I can take it from here.

**Pull request merged**
