### PR TITLE
plan: introduce the reload-free polling/progress pattern

### LINKED ISSUE #365: Upgrade the upload flow
Through the upload flow I see a few opportunities for a cleaner UX.

## upload page
* The text list of current supported states is BIG. (Also.. wow.. it's come a long way in the past couple months!) I could see it moving to a small caption below the SVG graphic.
* The filetypes chunk relates to the "Upload a district plan as a geospatial file containing Polygon or MultiPolygon shapes" sentence. Could reorder that a bit.
* having two buttons really throws me. at the very least I'd want the Score button to be disabled prior to a file being selected.  But I'd prefer having just a "Select a file to upload" button, where the upload begins immediately after filepicker selection.

## annotate stage
* I'd love to avoid asking the user to refresh. We could poll every ~3 seconds.

## scoring & plan
* Same bit about refresh. This part definitely takes longer (it took ~60s on my recent uploads). We could poll every 5s and provide more detail about progress. For example:

> ✅ Plan file uploaded
> ✅ Plan annotated
> ✅ Starting analysis
> ✅ Reading district geometries
> 🔄 Iterating slice subtotals: 0 / 44

And at completion, this progress UI would just disappear instantly in exchange for the plan content. Or, we could be slightly more gentle and provide a "Analysis complete" message, pause for a couple seconds, and then replace things with the plan.  

----

Thoughts?

### PR DESCRIPTION
**Pull request by paulirish**
(this PR is currently proposing a merge into #377 for a clean diff. but we can merge that first, or whatever.)

same deal as #377 but for the plan page. ref #365 . fixes #365 

Because I'm not running a backend for myself I couldn't test both sides, but I could test my frontend against prod backend.

Here's a mockup of what my latest upload would have looked like if we had both sides:

image

In previous uploads I see the 0% around for quite a while before the progress starts going. As a followup, I imagine we can find another place to set the message to better communicate progress?

----

In these PRs I'm making the broad assumption that tweaking these fixtures is kosher, but... lemme know if you want to take a different approach. :)

### CODE REVIEW

**Comment by migurski** [comment]
This is looking like a strict improvement to me, so … carry on. :)

It hangs out at 0% because it can take some time for the first sub-task to come back. It’s not great, I’m interested in talking through what an improvement might look like.

**Comment by migurski** [comment]
Nice. Before I merge this, do you have any notes on how I should structure the messages for an in-progress plan? I’ve been treating them as free text so far but I think you’ve introduced some structure. What should I think about if ever adding new ones?

**Comment by paulirish** [comment]
> Nice. Before I merge this, do you have any notes on how I should structure the messages for an in-progress plan? I’ve been treating them as free text so far but I think you’ve introduced some structure. What should I think about if ever adding new ones?


Right... so.. the current messages are the following, plus the [error cases you included here](https://github.com/PlanScore/PlanScore/issues/365#issuecomment-869964047).

```
Loading district plan.
Scoring: Starting analysis.
Scoring: {} complete.
Scoring: Adding up votes. Almost done.
Finished scoring this plan.
```

TBH the "Scoring: " prefix isn't important to the UI.  Those could be changed to proper sentences and everything would work out just fine.  (In fact, yeah, maybe more readable sentences would be an upgrade to what I did :)

The only thing the UI does is if it's about to log a message that's already been logged, then it just adds a `…` to that line instead. Given that, the only thing to keep in mind is that it'd be slightly odd if we logged the exact same message that's not the latest, eg. "Reading data" ... "Evaluating plan" ... "Reading data".  But.. the consequences of that aren't that bad, just added ellipsis on the non-last message. ;)

**Comment by migurski** [comment]
Got it, so I should still be able to treat these as free-form text. Merging!

**Pull request merged**
